<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <Version>0.1.0-alpha14</Version>
    <IsPackable>true</IsPackable>
    <OutputType>Library</OutputType>
    <PackageDescription>Experimental Deedle formatters for dotnet interactive notebooks</PackageDescription>
    <PackageReadmeFile>Readme.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/ingted/Deedle.DotNet.Interactive.Extension</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/ingted/Deedle.DotNet.Interactive.Extension</RepositoryUrl>
    <IncludeBuildOutput>true</IncludeBuildOutput>
    <NoWarn>$(NoWarn);NU5100</NoWarn><!-- dll outside of lib/ folder -->
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Formatting.fs" />
    <Compile Include="DFPrint.fs" />
    <Compile Include="Extension.fs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="bin\**" />
    <EmbeddedResource Remove="bin\**" />
    <None Remove="bin\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="10.1.201" />
    <PackageReference Include="Deedle" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\interactive\src\Microsoft.DotNet.Interactive\Microsoft.DotNet.Interactive.csproj" PrivateAssets="all" />
    <ProjectReference Include="..\..\..\interactive\src\Microsoft.DotNet.Interactive.Formatting\Microsoft.DotNet.Interactive.Formatting.csproj" PrivateAssets="all" />
    <ProjectReference Include="..\..\..\interactive\src\Microsoft.DotNet.Interactive.FSharp\Microsoft.DotNet.Interactive.FSharp.fsproj" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Include="$(OutputPath)/Deedle.DotNet.Interactive.Extension.dll" Pack="true" PackagePath="interactive-extensions/dotnet" />
    <None Include="..\..\Readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
